language: node_js
node_js:
- '6'
before_script:
- cd test
- npm install
script:
- npm test
env:
  matrix:
  - secure: tL7jseM6JkOeWKketQmL9O8rjO8CB+iXjZp8W3iBxnzhLciuKxFDWFoZUXG9MAJXj335S4K1bLJiW4IlPqt+r25nMEsOerobCDtByHUZgOKzAnvf1zGBul9QSLnz30AovVTebUcRFcMUuXYFF4Pe/dSuIVdFORp7eFH3pBA8mOpnFZ2gz1iKTvWzFVItcxwV2t4Y6/oMtiyrZLZSjNgOdotE6mI2buPrFQIA6lytGOP0PHOsSM+Yxa5OFVm/JHGIz+zS+9SjewllU3pnSZ9/mM0wHFABHchfpyh3ZRrugHJWzl5Srev8RdZy5jpqBzfRsLenHg8R4GMItWcrtZzj0K23LwfxCWcp6ZnRFvQ1lhHpmMo017XhNL+r2zj6/kRwmUWeNWxyRWOJ73e0cg9SFDm1h8I6rMOAHhdke++637TxMyf500mLoNUweXO6VogoBBWO0SaHPppSGAoUI8QW6MYNqFEAW3Oat5m7T/s4wfRbUu236qqn9QIYMSjkLfOrqLqs9kvp8aTvoZjpOT5x/MX/PTXQRtpkES6Zs2OfUhsDP5HsnKjMgdr9odEZSk+WTK58UKYtjlXk9+S3bjrWJ1uGuBAF3ElZs2zHnjT/uyFlh5TjgRdqdEjgqNwt6pV7+6RRtOxKIrOfVl4HCIqO+AQO+NRlXUYTBKrQGy2S/wc=
  - secure: kNH/47iz+pfm1ETEdQW4v9v6BOF/pMqO+FvlAK2RTshMV5pAF2cqCW7wCXxvb2QSd2i1r/LF6UommiWg0KfB+f6LVu8Qzw1TwALgNw/HR+7uMFhFGP0kbhno5ZnIv/d+nE76a93IGmDYppYKF5KHzYJ01ozDFp4I61IjmY48Vz2PQR2I5ApDZl4Fk++/vkCjr/1GesshYnZmy4fba1YfxB8CJcdYLFWAiE8OUa+X4BA436h2qwGMlJ466K1rSaUlnWF+HIXwRwpZB8nU3uRd/fyMFa/j8MEBTWLrOcAKVOu8tWVFC5o1Ucnh2E2TvT1/32NeFq4w6K6PInXMBWumwcV0t+6k2W4z9dhpFqNT51rtGS88q6eYewLReSYjhnx5wM2qE2cUsZaPb7l/Uq8fi//yDqJJC1uWO2m9i7mEcxTZ7um6N/VvI4PaGVlDpFU2zbgH7wv+XnYBP605gDUulwUtTCR1HMmQmskJToeN0h62Mivr4OFvWZPknYRyE6FU7xmF0Vsb7a5npztAFldtkhGC79WNXTZrJYRXPWUyTrxOKZKNDScppSJ5sztwCCviCFfuwmylQL1Gfc48YyOaHuynooMpQbo1UAKiEDSn6KsFc840ZQBu2uRQTIonJcpRWF+ygCgbP4w74rk/WhfsL8bYzyCbn7Ni+JllqM7LXCo=
